name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'
jobs:
  build-and-push:
    strategy:
      matrix:
        postgres_version: [12, 13, 14, 15, 16, 17]
        variant: [alpine3.20, alpine3.21, bookworm, bullseye, latest]
    uses: SirSplat/workflows/.github/workflows/build-and-push-docker-image.yaml@main
    with:
      directory: ${{ matrix.postgres_version }}/${{ matrix.variant }}
      image_name: postgresql
      tag: ${{ matrix.postgres_version }}-${{ matrix.variant }}
      runner_debug: false
      step_debug: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
